plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.142'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

repositories {
    maven { url = 'https://maven.createmod.net' }
    maven { url = 'https://maven.blamejared.com' }
    mavenCentral()
}

neoForge {
    version = neo_version

    runs {
        client {
            client()
            gameDirectory = project.file('runs/client')
        }
        server {
            server()
            gameDirectory = project.file('runs/server')
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    implementation "com.simibubi.create:create-${minecraft_version}:${create_version}:slim@jar"
    implementation files(fileTree(dir: 'libs/create-embedded/META-INF/jarjar', include: ['*.jar']))
    compileOnly "mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}"
    runtimeOnly "mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}